### ISSUE TITLE
What's new in version 3?

### ISSUE THREAD

**Issue by rvalitov** [FrDH/jQuery.dotdotdot#135]
Hello!
In the release of the version 3.x it's specified that the plugin is completely rewritten. Can you please provide more details: is there any new functionality or is it better in some sort than the older 2.x version? The version 2.x was great, is there any advantages of version 3.x apart from "tidy code" and similar things? I ask these questions, because I think it will help a lot to existing users of your plugin to make a decision if it's worth upgrading or not. Thank you!!

**Comment by rlenders** [comment]
I'm curious too. Right now I'm considering using 2.x, because the performance of 3.x seems to be much worse than 1.8.3. I'm wondering what I'll be missing out on.

**Comment by FrDH** [comment]
Here's a list of things that changed since 1.8.3:

* The truncation process was re-written to calculate where to put the ellipsis more precise. In 1.8 the ellipsis was somethimes not added at all.
* The `after` option is replaced with `keep` which can point to more than one element. The elements are now kept in there original place in the DOM instead of always being appended after the ellipsis.
* The custom events are replaced with an API
* The `watch` option is set to "window" by default
* jQueries `html` and `text` methods are no longer overridden
* Initiallisation via classnames and data-attributes is removed
* The `wrap` and `fallbackToLetter` options are combined into `truncate`
* The `height` option is removed because the plugin now understands `height`, `min-height` and `max-height` CSS values

**Comment by rlenders** [comment]
Thanks!
