### ISSUE TITLE
callback isTruncated returns false although text was truncated

### ISSUE THREAD

**Issue by Px-Factor** [FrDH/jQuery.dotdotdot#150]
In an edge case, if the first paragraph of the truncated text matches the height passed with the parameters for dotdotdot, the callback function returns isTruncated as false, although the rest of the html is actually truncated and everything else (restore()) seems to work well. I rely on isTruncated to know whether I should display a "show more" button or not.

As a side note, the ellipsis that is added to the end of the truncated string is also not added in this case.

Workaround for me for now was to change the size of the font, but this could create issues in the future when the customer updates the content of the website.

Edit: this is with version 3.1.0 downloaded today fromdotdotdot.frebsite.nl.

**Comment by FrDH** [comment]
Sounds odd, I'll have to check.
Thank you for bringing it to my attention.

**Comment by Vilial** [comment]
Confirm. Version 3.1.0
isTruncated is false in some situations though the text actually was truncated. Though in my case the passed height was 300px and 4 paragraphs left after the truncation are 305px.
http://joxi.ru/1A511wRuK5EPYA?d=1
If I resize the window on this same page in order to slightly change the height of the text I get the correct behaviour.

**Comment by FrDH** [comment]
Should be fixed in 3.2.0
Could you try?

**Comment by Px-Factor** [comment]
Issue seems to be resolved for me with version 3.2.1
